<main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">
    <div class="main-navbar sticky-top bg-white">
        <!-- Main Navbar -->
        <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
        <form action="#" class="main-navbar__search w-100 d-none d-md-flex d-lg-flex">
            <div class="input-group input-group-seamless ml-3">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <i class="fas fa-search"></i>
                    </div>
                </div>
                <input class="navbar-search form-control" type="text" placeholder="Search for something..." aria-label="Search">
            </div>
        </form>
        <nav class="nav">
            <a href="#" class="nav-link nav-link-icon toggle-sidebar d-md-inline d-lg-none text-center border-left" data-toggle="collapse" data-target=".header-navbar" aria-expanded="false" aria-controls="header-navbar">
                <i class="material-icons">&#xE5D2;</i>
            </a>
        </nav>
        </nav>
    </div>
    <!-- / .main-navbar -->
    <div class="main-content-container container-fluid px-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <span class="text-uppercase page-subtitle">Dashboard</span>
                <h3 class="page-title">CONSULTAS MEDICAS</h3>
            </div>
        </div>
        <!-- End Page Header -->
        <div class="row">
            
            <!-- TBL Bitacora -->
            <div class="row bitacora-dash" style="width: 100%">
                <div class="col">
                    <div class="card card-small mb-4">
                        <div class="card-header border-bottom">
                            <button type="button" class="btn btn-info add-bitacora">
                                <i class="fas fa-file-medical fa-lg"></i>&nbsp;<span>Bitacora</span>
                            </button>
                        </div>
                        <div class="card-body p-0 pb-3 text-center">
                            <table class="table mb-0" id="tbl_filters" style="width: 70%">
                                <thead class="bg-light">
                                    <tr>
                                        <th class="border-0" scope="col">Filtrar por Area</th>
                                        <th class="border-0" scope="col">Filtrar por Fechas</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td scope="col">
                                            <select class="custom-select filter_area inputSize"  id="filter_area">
                                                <option value="0">Seleccionar una Opcion</option>
                                            </select>
                                        </td>
                                        <td scope="col">
                                            <div id="bitacora-date-range" class="input-daterange input-group input-group-sm my-auto ml-auto mr-auto ml-sm-auto mr-sm-0" style="max-width: 350px;">
                                                <input type="text" class="input-sm form-control" name="start" placeholder="Start Date" id="date-range-1" data-toggle="tooltip" data-placement="top" title="Fecha Desde..">
                                                <input type="text" class="input-sm form-control" name="end" placeholder="End Date" id="date-range-2" data-toggle="tooltip" data-placement="top" title="Fecha Hasta..">
                                                <span class="input-group-append">
                                                    <span class="input-group-text">
                                                        <i class="material-icons"></i>
                                                    </span>
                                                </span>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td scope="col">
                                            <button type="button" class="btn btn-info search-bit" data-toggle="tooltip" data-placement="top" title="Filtrar Información..">
                                                <i class="fas fa-search fa-lg"></i>
                                            </button>
                                            &nbsp;&nbsp;
                                            <button type="button" class="btn btn-success exp-bit" data-toggle="tooltip" data-placement="top" title="Exportar Información..">
                                                <i class="fas fa-file-export"></i>
                                            </button>
                                            &nbsp;&nbsp;
                                            <label class="btn btn-warning" for="ImpBit" style="margin-top: 9px" data-toggle="tooltip" data-placement="top" title="Importar desde un CSV">
                                                <input id="ImpBit" type="file" style="display:none;">
                                                <i class="fas fa-download" aria-hidden="true">
                                                </i>
                                            </label>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="card-body p-0 pb-3 text-center">
                            <table class="table mb-0" id="tbl_bitacora">
                                <thead class="bg-light">
                                    <tr>
                                        <th class="border-0" scope="col" style="width: 111px;"></th>
                                        <th class="border-0" scope="col">Fecha</th>
                                        <th class="border-0" scope="col">Hora</th>
                                        <th class="border-0" scope="col">Nombre</th>
                                        <th class="border-0" scope="col">Sexo</th>
                                        <th class="border-0" scope="col">Area</th>
                                        <th class="border-0" scope="col">#Empleado</th>
                                        <th class="border-0" scope="col">Supervisor</th>
                                        <th class="border-0" scope="col">Diagnostico</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End TBL Bitacora -->

            <!-- TBL Agenda -->
            <div class="row agenda-dash" style="display: none; width: 100%">
                <div class="col">
                    <div class="card card-small mb-4">
                        <div class="card-header border-bottom">
                            <button type="button" class="btn btn-info add-contacto">
                                <i class="fas fa-user-plus fa-lg"></i>&nbsp;<span>Agregar Contacto</span>
                            </button>
                        </div>
                        <div class="card-body p-0 pb-3 text-center">
                            <table class="table mb-0 table-responsive" id="tbl_agenda">
                                <thead class="bg-light">
                                    <tr>
                                        <th class="border-0" scope="col" style="width: 111px;"></th>
                                        <th scope="col">Nombre</th>
                                        <th scope="col">Apellidos</th>
                                        <th scope="col">Direccion</th>
                                        <th scope="col">Telefonos</th>
                                        <th scope="col">Fecha de Creacion</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End TBL agenda -->

            <div class="row graph-med" style="display: none; width:100%">
                <!-- Users Stats -->
                <div class="col-lg-8 col-md-12 col-sm-12 mb-4">
                    <div class="card card-small">
                        <div class="card-header border-bottom">
                            <h6 class="m-0">Users</h6>
                        </div>
                        <div class="card-body pt-0">
                            <div class="row border-bottom py-2 bg-light">
                                <div class="col-12 col-sm-6">
                                    <div id="blog-overview-date-range" class="input-daterange input-group input-group-sm my-auto ml-auto mr-auto ml-sm-auto mr-sm-0" style="max-width: 350px;">
                                        <input type="text" class="input-sm form-control" name="start" placeholder="Start Date" id="blog-overview-date-range-1">
                                        <input type="text" class="input-sm form-control" name="end" placeholder="End Date" id="blog-overview-date-range-2">
                                        <span class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="material-icons"></i>
                                            </span>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6 d-flex mb-2 mb-sm-0">
                                    <button type="button" class="btn btn-sm btn-white ml-auto mr-auto ml-sm-auto mr-sm-0 mt-3 mt-sm-0">View Full Report &rarr;</button>
                                </div>
                            </div>
                            <canvas height="130" style="max-width: 100% !important;" class="blog-overview-users"></canvas>
                        </div>
                    </div>
                </div>
                <!-- End Users Stats -->
                <!-- Users By Device Stats -->
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="card card-small h-100">
                        <div class="card-header border-bottom">
                            <h6 class="m-0">Users by device</h6>
                        </div>
                        <div class="card-body d-flex py-0">
                            <canvas height="220" class="blog-users-by-device m-auto"></canvas>
                        </div>
                        <div class="card-footer border-top">
                            <div class="row">
                                <div class="col">
                                    <select class="custom-select custom-select-sm" style="max-width: 130px;">
                                        <option selected>Last Week</option>
                                        <option value="1">Today</option>
                                        <option value="2">Last Month</option>
                                        <option value="3">Last Year</option>
                                    </select>
                                </div>
                                <div class="col text-right view-report">
                                    <a href="#">Full report &rarr;</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Users By Device Stats -->
            </div>
        
        </div>

        <!-- Begin Modals -->
        <div class="row">
            <div id="modal-add-agenda" class="modal" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg" role="document" style="width: 70%;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Agregar Elemento a la Agenda</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-8 order-md-1">
                                    <form>
                                    <div class="row">
                                    
                                            <div class="col-md-6 mb-3">
                                            <label for="nombre">Nombre</label>
                                            <input type="text" class="form-control" id="nombre" placeholder="" value="" required="true">
                                            </div>
    
                                            <div class="col-md-6 mb-3">
                                            <label for="apellidos">Apellidos</label>
                                            <input type="text" class="form-control" id="apellidos" placeholder="" value="" required="true">
                                            </div>
                                    </div>
    
                                    <div class="mb-3">
                                            <label for="dir">Direccion</label>
                                            <input type="text" class="form-control" id="dir" placeholder="1234 Main St" required="true">
                                    </div>
    
                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="telefono">Telefono</label>
                                            <input type="text" class="form-control" id="telefono" placeholder="" value="" required="true">
                                            </div>
    
                                            <div class="col-md-2 mb-3">
                                                <label for="add-phone">AgregarTelefono</label>
                                            <button class="btn btn-primary" id="add-phone" type="button"><i class="fas fa-plus"></i></button>
                                            </div>
                                    </div>
    
                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="nombre">Telefonos</label>
                                            <table class="table mb-0" id="list-telefonos">
                                                <thead class="bg-light">
                                                    <th>Telefono</th>
                                                    <th></th>
                                                </thead>
                                                <tbody></tbody>
                                            </table>
                                        </div>
                                    </div>
    
                                    <hr class="mb-4">
                                    <button class="btn btn-outline-success" id="save-item" type="button">Guardar</button>
                                    </form>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary cerrar" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Begin AddBitacora -->
            <div id="modal-add-bitacora" class="modal" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg" role="document" style="width: 70%;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title title-modal-bit">Agregar Bitacora</h5>
                            <button type="button" class="close close-bitacora" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-8 order-md-1">
                                <form>
                                    <div id="FormBitacora">
                                        <div class="row">
                                            <div class="col-md-8 mb-3">
                                                <h4>Fecha: <span class="badge badge-secondary fec-bitacora"></span></h4>
                                            </div>
                                        </div>
                                        <div class="row" style="width:700px">
                                            <div class="col-md-8 mb-3">
                                                <div class="input-group mb-3">
                                                    <div class="input-group-prepend">
                                                        <label class="input-group-text" for="SelectEmpleado">
                                                            Num. Empleado
                                                        </label>
                                                    </div>
                                                    <select class="custom-select SelectEmpleado" id="SelectEmpleado" style="width:200px">
                                                        <option selected value="0">Seleccionar...</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="mb-3" id="InfoEmpleado" style="display:none">

                                            </div>
                                        </div>
    
                                        <div class="row" style="width:700px">
                                            <div class="col-md-6 mb-3">
                                                <div class="input-group mb-3">
                                                    <div class="input-group-prepend">
                                                        <label class="input-group-text" for="SelectSupervisor">Supervisor</label>
                                                    </div>
                                                    <select class="custom-select" id="SelectSupervisor" style="width:200px">
                                                    </select>
                                                    <button class="btn btn-danger add-supervisor" data-toggle="tooltip" data-placement="top" title="Agregar un Supervisor..">
                                                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                                    </button>
                                                </div>
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <div class="input-group mb-3">
                                                    <div class="input-group-prepend">
                                                        <label class="input-group-text" for="SelectClasificacion">Clasificacion</label>
                                                    </div>
                                                    <select class="custom-select" id="SelectClasificacion" style="width:200px">
                                                    </select>
                                                    <button class="btn btn-danger add-clasif" data-toggle="tooltip" data-placement="top" title="Agregar clasificación..">
                                                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
    
                                        <div class="row">
                                            <div class="col-md-6 mb-3">
                                                <label for="SelectTurno">Turno</label>
                                                <select class="custom-select" id="SelectTurno">
                                                    <option value="1">1</option>
                                                    <option value="2">2</option>
                                                    <option value="3">3</option>
                                                </select>
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="SelectAtendio">Atendio</label>
                                                <select class="custom-select" id="SelectAtendio">
                                                </select>
                                            </div>
                                        </div>
    
                                        <div class="row">
                                            <div class="col-md-6 mb-3">
                                                <label for="diagnostico">Diagnostico</label>
                                                <textarea id="diagnostico" class="form-control"></textarea>
                                            </div>
                                        </div>
        
                                        <hr class="mb-4">
                                        <button class="btn btn-outline-success" id="save-bitacora" type="button">Guardar</button>
                                        <button class="btn btn-outline-primary" id="upd-bitacora" type="button" style="display: none;" data-toggle="tooltip" data-placement="top" title="Actualizar">
                                            Actualizar
                                        </button>
                                        <button class="btn btn-danger" id="cancel-upd" type="button" style="display: none;" data-toggle="tooltip" data-placement="top" title="Cancelar Actualizacion">
                                            <i class="fas fa-ban"></i>
                                        </button>
                                    </div>

                                    <div class="row" id="DetailFormBitacora" style="display: none">
                                        <div class="col-md-6 mb-3 InfoPaciente">
                                            
                                        </div>
                                        <div class="col-md-6 mb-3 InfoBitacora">
                                            
                                        </div>
                                    </div>
    
                                    <div class="row addMedBit" style="display:none">
                                        <div class="col-md-6 mb-3">
                                            <label for="SelectMedicamento">Medicamento</label>
                                            <select class="custom-select" id="SelectMedicamento" style="width: 200px">
                                            </select>
                                        </div>
                                        <div class="col-md-6 mb-3 TotQuantity" style="display: none">
                                            <label for="TotQuantity">Cantidad</label>
                                            <input type="text" name="TotQuantity" id="TotQuantity" class="form-control" placeholder="" value="" required="true" style="width: 100px">
                                        </div>
                                    </div>
    
                                    <div class="row addMedBit" style="display:none">
                                        <div class="col-md-6 mb-3">
                                            <button type="button" class="btn btn-warning add-med-bit" data-toggle="tooltip" data-placement="top" title="Agregar medicamentos a la bitacora..">
                                                <span>Agregar Medicamento</span>&nbsp;<i class="fas fa-cart-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                    

                                    <!-- TBL Bitacora -->
                                    <div class="row col-md-6 addMedBit" style="display:none;">
                                        <table class="table mb-0" id="tbl_bitmed">
                                            <thead class="bg-light">
                                                <tr>
                                                    <th scope="col"></th>
                                                    <th scope="col">Tipo Med.</th>
                                                    <th scope="col">Presentacion</th>
                                                    <th scope="col">Medicamento</th>
                                                    <th scope="col">Cantidad</th>
                                                    <th scope="col">Fecha Creacion</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- End TBL Bitacora -->
                                </form>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary close-bitacora" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End AddBitacora -->
            <div id="modal-edit-agenda" class="modal" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg" role="document" style="width: 70%;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Editar Direccion</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-8 order-md-1">
                                    <form>
                                    <div class="row">
                                    
                                            <div class="col-md-6 mb-3">
                                            <label for="nombre-edit">Nombre</label>
                                            <input type="text" class="form-control" id="nombre-edit" placeholder="" value="" required="true">
                                            </div>

                                            <div class="col-md-6 mb-3">
                                            <label for="apellidos-edit">Apellidos</label>
                                            <input type="text" class="form-control" id="apellidos-edit" placeholder="" value="" required="true">
                                            </div>
                                    </div>

                                    <div class="mb-3">
                                            <label for="dir-edit">Direccion</label>
                                            <input type="text" class="form-control" id="dir-edit" placeholder="1234 Main St" required="true">
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="telefono-edit">Telefono</label>
                                            <input type="text" class="form-control" id="telefono-edit" placeholder="" value="" required="true">
                                            </div>

                                            <div class="col-md-2 mb-3">
                                                <label for="edit-phone">Editar</label>
                                            <button class="btn btn-primary" id="edit-phone" type="button"><i class="fas fa-plus"></i></button>
                                            </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="edit-tbl-telefonos">Telefonos</label>
                                            <table class="table" id="list-telefonos-edit">
                                                <thead>
                                                    <th>Telefono</th>
                                                    <th></th>
                                                </thead>
                                                <tbody></tbody>
                                            </table>
                                            </div>
                                    </div>

                                    <hr class="mb-4">
                                    <input type="hidden" id="idagenda-edit">
                                    <button class="btn btn-outline-success" id="update-item" type="button">Guardar</button>
                                    </form>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary edit-close" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>
            
            <div id="modal-add-personalmed" class="modal" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg" role="document" style="width: 70%;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Agregar Personal Medico</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-8 order-md-1">
                                <form>
                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="nombre">Nombre</label>
                                            <input type="text" class="form-control" id="nomb_personal" placeholder="" value="" required="true">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="apellidos">Apellido Paterno</label>
                                            <input type="text" class="form-control" id="ape_pat" placeholder="" value="" required="true">
                                        </div>

                                        <div class="col-md-6 mb-3">
                                            <label for="apellidos">Apellido Materno</label>
                                            <input type="text" class="form-control" id="ape_mat" placeholder="" value="" required="true">
                                        </div>
                                    </div>

                                    <div class="mb-3">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <label class="input-group-text" for="SelectTitulo">Titulo</label>
                                            </div>
                                            <select class="custom-select" id="SelectTitulo">
                                                <option selected value="0">Seleccionar...</option>
                                                <option selected value="Dr.">Dr.</option>
                                                <option selected value="Dra.">Dra.</option>
                                                <option selected value="Enfermero/a">Enfermero/a</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="mb-3">
                                        <hr class="mb-4">
                                        <button class="btn btn-outline-success" id="save-item-med" type="button">Guardar</button>
                                        <button class="btn btn-outline-info" id="upd-item-med" type="button" style="display: none;">
                                            Actualizar
                                        </button>
                                        <button class="btn btn-outline-info" id="clean-item-med" type="button">
                                            <i class="fas fa-recycle"></i>
                                        </button>
                                    </div>
                                </form>
                            </div>
                            <br>
                            <div class="col-lg-12">
                                <table class="table mb-0" id="tbl_personalmed">
                                    <thead class="bg-light">
                                        <tr>
                                            <th scope="col"></th>
                                            <th scope="col">Nombre</th>
                                            <th scope="col">Apellido Paterno</th>
                                            <th scope="col">Apellido Materno</th>
                                            <th scope="col">Fecha Creacion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary cerrar" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>

            <div id="modal-add-empleados" class="modal" role="dialog">
                <div class="modal-dialog modal-lg med" role="document" style="width: 70%;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Agregar Empleados</h5>
                            <button type="button" class="close close-mod-emp" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-6 mb-3">
                                <a class="btn btn-primary" data-toggle="collapse" href="#form-emp" role="button" aria-expanded="false" aria-controls="form-emp">
                                    <i class="fas fa-user-plus"></i> Agregar Empleados
                                </a>
                            </div>
                            <div class="col-md-8 order-md-1 collapse hide" aria-labelledby="headingOne" data-parent="#modal-add-personalmed" id="form-emp">
                                <form>
                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="num_emp">Numero de Empleado</label>
                                            <input type="text" class="form-control" id="num_emp" placeholder="" value="" required="true">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="nomb_personal">Nombre</label>
                                            <input type="text" class="form-control" id="nomb_emp" placeholder="" value="" required="true">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="ape_pat">Apellido Paterno</label>
                                            <input type="text" class="form-control" id="ape_pat_emp" placeholder="" value="" required="true">
                                        </div>

                                        <div class="col-md-6 mb-3">
                                            <label for="ape_mat">Apellido Materno</label>
                                            <input type="text" class="form-control" id="ape_mat_emp" placeholder="" value="" required="true">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="mb-3">
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <label class="input-group-text" for="sexo">
                                                        Sexo
                                                    </label>
                                                </div>
                                                <select class="custom-select SelectSexo sexo" id="sexo">
                                                    <option value="M">Masculino</option>
                                                    <option value="F">Femenino</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row" style="width: 700px;">
                                        <div class="mb-3">
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <label class="input-group-text" for="sel_area">
                                                        Area
                                                    </label>
                                                </div>
                                                <select class="custom-select SelectArea inputSize" id="sel_area">
                                                </select>
                                                <button class="btn btn-danger add-emp-area" data-toggle="tooltip" data-placement="top" title="Agregar un nuevo elemento..">
                                                    <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                                </button>
                                            </div>
                                        </div>
                                        &nbsp;&nbsp;
                                        <div class="mb-3">
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <label class="input-group-text" for="sel_dpto">
                                                            Departamento
                                                    </label>
                                                </div>
                                                <select class="custom-select sel_dpto" id="sel_dpto">
                                                </select>
                                                <button class="btn btn-danger add-emp-dpto" data-toggle="tooltip" data-placement="top" title="Agregar un nuevo elemento..">
                                                    <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="actividad">Actividad</label>
                                            <input type="text" class="form-control" id="actividad" placeholder="" value="" required="true">
                                            </div>

                                            <div class="col-md-6 mb-3">
                                                <label for="antiguedad">Antiguedad</label>
                                            <input type="text" class="form-control" id="antiguedad" placeholder="" value="" required="true">
                                        </div>
                                    </div>

                                    <div class="mb-3">
                                        <hr class="mb-4">
                                        <button class="btn btn-outline-success" id="save-emp" type="button" data-toggle="tooltip" data-placement="top" title="Guardar la Información capturada">Guardar</button>
                                        <label class="btn btn-outline-success" for="UploadCSV" style="margin-top: 9px" data-toggle="tooltip" data-placement="top" title="Importar desde un CSV">
                                            <input id="UploadCSV" type="file" style="display:none;">
                                            <i class="fas fa-file-excel" aria-hidden="true">
                                            </i>
                                        </label>
                                        <button class="btn btn-outline-info" id="upd-emp" type="button" style="display: none;" data-toggle="tooltip" data-placement="top" title="Actualizar">
                                            Actualizar
                                        </button>
                                        <button class="btn btn-outline-info" id="clean-emp" type="button" data-toggle="tooltip" data-placement="top" title="Limpiar Campos">
                                            <i class="fas fa-recycle"></i>
                                        </button>
                                    </div>
                                </form>
                            </div>
                            <br>
                            <div class="col-lg-12">
                                <table class="table mb-0" id="tbl_emp">
                                    <thead class="bg-light">
                                        <tr>
                                            <th scope="col"></th>
                                            <th scope="col">Num. Empleado</th>
                                            <th scope="col">Nombre</th>
                                            <th scope="col">Apellido Paterno</th>
                                            <th scope="col">Apellido Materno</th>
                                            <th scope="col">Area</th>
                                            <th scope="col">Fecha Creacion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary close-mod-emp" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>

            <div id="modal-add-medicamento" class="modal" role="dialog">
                <div class="modal-dialog modal-lg med" role="document" style="width: 90%;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Agregar Medicamentos</h5>
                            <button type="button" class="close close-mod-medic" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-8 order-md-1">
                                <form>
                                    <div class="mb-3">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <label class="input-group-text" for="AddClasifMed">
                                                Clasif. de Med.
                                                </label>
                                            </div>
                                            <select class="custom-select ClasifMed inputSize" id="AddClasifMed" style="width: 40%">
                                            </select>
                                            <button class="btn btn-danger add-clasif-med" data-toggle="tooltip" data-placement="top" title="Agregar nueva clasificacion..">
                                                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="DescripcionMedicamento">Medicamento y/o Procedimiento</label>
                                            <input type="text" class="form-control" id="DescripcionMedicamento" placeholder="" value="" required="true">
                                        </div>
                                    </div>

                                    <div class="row totales" style="display:none">
                                        <div class="col-md-6 mb-3">
                                            <label for="InvMinimo">Cantidad minima</label>
                                            <input type="text" class="form-control" id="InvMinimo" placeholder="" value="" required="true" style="width: 50%;">
                                        </div>

                                        <div class="col-md-6 mb-3">
                                            <label for="Inventario">Inventario</label>
                                            <input type="text" class="form-control" id="Inventario" placeholder="" value="" required="true" style="width: 50%;">
                                        </div>
                                    </div>
                                
                                    <div class="row totales" style="display:none">
                                        <div class="col-md-6 mb-3">
                                            <label for="PresentacionMed">Presentacion</label>
                                            <select class="custom-select PresentacionMed inputSize" id="PresentacionMed" style="width: 80%;">
                                                <option value="0">Seleccionar una opcion..</option>
                                                <option value="NA">NA</option>
                                                <option value="ml">Mililitros</option>
                                                <option value="mg">Mililitros</option>
                                                <option value="tab">Tableta</option>
                                                <option value="cap">Capsula</option>
                                                <option value="pza">Pieza</option>
                                            </select>
                                        </div>

                                        <div class="col-md-6 mb-3">
                                            <label for="CantPresentacion">Cantidad X Presentacion</label>
                                            <input type="text" class="form-control" id="CantPresentacion" placeholder="" value="" required="true" style="width: 50%;">
                                        </div>
                                    </div>

                                    <div class="mb-3">
                                        <hr class="mb-4">
                                        <button class="btn btn-outline-success" id="save-cmed" type="button" data-toggle="tooltip" data-placement="top" title="Guardar la Información capturada">Guardar</button>
                                        <button class="btn btn-outline-info" id="upd-cmed" type="button" style="display: none;" data-toggle="tooltip" data-placement="top" title="Actualizar">
                                            Actualizar
                                        </button>
                                        <button class="btn btn-outline-info" id="clean-cmed" type="button" data-toggle="tooltip" data-placement="top" title="Limpiar Campos">
                                            <i class="fas fa-recycle"></i>
                                        </button>
                                        <label class="btn btn-warning" for="UploadCSVMed" style="margin-top: 9px" data-toggle="tooltip" data-placement="top" title="Importar desde un CSV">
                                            <input id="UploadCSVMed" type="file" style="display:none;">
                                            <i class="fas fa-file-excel" aria-hidden="true">
                                            </i>
                                        </label>
                                    </div>
                                </form>
                            </div>
                            <br>
                            <div class="col-lg-12">
                                <table class="table mb-0" id="tbl_cmed">
                                    <thead class="bg-light">
                                        <tr>
                                            <th scope="col"></th>
                                            <th scope="col">Clasificacion Medicamento</th>
                                            <th scope="col">Descripcion</th>
                                            <th scope="col">Presentacion</th>
                                            <th scope="col">Cantidad de Presentacion</th>
                                            <th scope="col">Inventario Minimo</th>
                                            <th scope="col">Inventario Total</th>
                                            <th scope="col">Fecha Creacion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary close-mod-medic" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Modals -->
    </div>
</main>