<?php 
include_once "db/db.php";
//include_once "dataLayer/libs/utils.php";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content=""/>
    <link rel="shortcut icon" href="javascript:;" type="image/png">

    <title>Grupo Medico ISRI</title>
    </style>

    <!--common style-->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" href="assets/css/alertify.min.css"/>
    <!-- Default theme -->
    <link rel="stylesheet" href="assets/css/themes/default.min.css"/>
    <!-- Semantic UI theme -->
    <link rel="stylesheet" href="assets/css/themes/semantic.min.css"/>
    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="assets/css/themes/bootstrap.min.css"/>
    <link rel="stylesheet" href="assets/css/select2.min.css"/>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link href="assets/css/style.css" rel="stylesheet">
</head>
<body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
        <a class="navbar-brand" href="#">
            <img src="assets/img/isri.png">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <button type="button" class="btn btn-light add-agenda">
                    <i class="fas fa-plus"></i>
                    <span>Agenda</span>
                </button>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Catalogos
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#" id="personal-med">
                        <i class="fas fa-plus"></i>
                        <span>Personal Medico</span>
                    </a>
                    <a class="dropdown-item" href="#" id="empleados">
                        <i class="fas fa-plus"></i>
                        <span>Empleados</span>
                    </a>

                    <a class="dropdown-item" href="#" id="empleados">
                        <i class="fas fa-plus"></i>
                        <span>Medicamentos y Procedimientos</span>
                    </a>
                </div>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <?php include("container.phtml") ?>

    <script type="text/javascript" src="assets/js/alertify.min.js"></script>
    <script type="text/javascript" src="assets/js/underscore-min.js"></script>
    <script type="text/javascript" src="assets/js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="assets/js/bootstrap-switch.min.js"></script>
    <script type="text/javascript" src="assets/js/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="assets/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="assets/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" src="assets/js/notify.js"></script>
    <script type="text/javascript" src="assets/js/pace.js"></script>
    <script type="text/javascript" src="assets/js/papaparse.js"></script>
    <script type="text/javascript" src="assets/js/select2.min.js"></script>
    <script type="text/javascript" src="assets/js/moment.min.js"></script>
    <script type="text/javascript" src="assets/js/popper.min.js"></script>
    <script type="text/javascript" src="assets/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js" integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ" crossorigin="anonymous"></script>
    <script type="text/javascript" src="scripts/index.js"></script>
</body>