<!doctype html>
<html class="no-js h-100" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>BITMedica</title>
    <meta name="description" content="A high-quality &amp; free Bootstrap admin dashboard template pack that comes with lots of templates and components.">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" id="main-stylesheet" data-version="1.0.0" href="styles/shards-dashboards.1.0.0.min.css">
    <link rel="stylesheet" href="styles/extras.1.0.0.min.css">
    <script async defer src="https://buttons.github.io/buttons.js"></script>
  </head>
  <body class="h-100">
      <div class="container-fluid">
         <div class="row">
         <!-- Main Sidebar -->
         <aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
               <div class="main-navbar">
                  <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
                  <a class="navbar-brand w-100 mr-0" href="#" style="line-height: 25px;">
                     <div class="d-table m-auto">
                     <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 25px;" src="images/shards-dashboards-logo.svg" alt="Shards Dashboard">
                     <span class="d-none d-md-inline ml-1">BitMedica</span>
                     </div>
                  </a>
                  <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                     <i class="material-icons">&#xE5C4;</i>
                  </a>
                  </nav>
               </div>
               <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
                  <div class="input-group input-group-seamless ml-3">
                  <div class="input-group-prepend">
                     <div class="input-group-text">
                     <i class="fas fa-search"></i>
                     </div>
                  </div>
                  <input class="navbar-search form-control" type="text" placeholder="Search for something..." aria-label="Search"> </div>
               </form>
               <div class="nav-wrapper">
                  <ul class="nav flex-column">
                     <li class="nav-item">
                        <a class="nav-link active" href="index.php">
                        <i class="material-icons">edit</i>
                        <span>Dashboard</span>
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link " href="#">
                        <i class="fas fa-user-circle"></i>
                        <span>Agenda</span>
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link " href="#">
                        <i class="fas fa-users"></i>
                        <span>Empleados</span>
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link " href="#">
                        <i class="fas fa-medkit"></i>
                        <span>Medicamentos</span>
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link " href="#">
                        <i class="fas fa-user-md"></i>
                        <span>Personal Medico</span>
                        </a>
                     </li>
                  </ul>
               </div>
         </aside>
         <!-- End Main Sidebar -->
         <?php include("container.phtml") ?>
         </div>
      </div>
   <script type="text/javascript" src="js/alertify.min.js"></script>
   <script type="text/javascript" src="js/underscore-min.js"></script>
   <script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
   <script type="text/javascript" src="js/bootstrap-switch.min.js"></script>
   <script type="text/javascript" src="js/jquery-3.3.1.js"></script>
   <script type="text/javascript" src="js/jquery.dataTables.min.js"></script>
   <script type="text/javascript" src="js/dataTables.bootstrap4.min.js"></script>
   <script type="text/javascript" src="js/notify.js"></script>
   <script type="text/javascript" src="js/pace.js"></script>
   <script type="text/javascript" src="js/papaparse.js"></script>
   <script type="text/javascript" src="js/select2.min.js"></script>
   <script type="text/javascript" src="js/moment.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
   <script src="https://unpkg.com/shards-ui@latest/dist/js/shards.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/Sharrre/2.0.1/jquery.sharrre.min.js"></script>
   <script src="scripts/extras.1.0.0.min.js"></script>
   <script src="scripts/shards-dashboards.1.0.0.min.js"></script>

   <script type="text/javascript" src="scripts/BITMedica/GenericFunctions.js"></script>
   <script type="text/javascript" src="scripts/BITMedica/Bitacora.js"></script>
  </body>
</html>